<?php

namespace st\firstBundle\Repository;

use Doctrine\ORM\EntityRepository ;
/**
 * continentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class continentsRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT a FROM stFirstBundle:continents a ORDER BY a.nom ASC")
            ->getResult() ;
    }


    public function findContinent($id )
    {     $em = $this->getDoctrine()
               ->getManager() ;
        $query= $em->createQuery("SELECT a FROM stFirstBundle:continents  WHERE a.id=$id") ;

        return $query->getResult() ;


    }

    public function getPopulation($id)
    {

    }



}



