<?php

namespace st\firstBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * paysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paysRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM stFirstBundle:pays a ORDER BY a.nom ASC')
            ->getResult() ;
        }*/



    public function getListPays($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('a')

            ->getQuery()
        ;

        $query
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
        ;

        return new Paginator($query, true);
    }

    public function findArrayPays($id )
    {
        return $this
            ->createQueryBuilder('a')
            ->select("a.nom AS label ,a.population AS data")
            ->where('a.continent = :id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();
    }
}


