# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        st\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:      [ROLE_USER, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username

#            entity:
#                    class:    OC\UserBundle\Entity\User
#                    property: username




#        in_memory:
#            memory:
#                users:
#                    user:   {password: userpass, roles:['ROLE_USER']}
#                    admin:  {password:  adminpass, roles: ['ROLE_ADMIN']}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern: ^/login$
            anonymous: true

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: /
            remember_me:
                secret: %secret%
        secured_area:
             form_login:
                 csrf_token_generator: security.csrf.token_manager

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
         #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }



       ##### main:
           ## anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
